<?php
namespace AzahariZaman\Dosys\Updates;

use Seeder;
use AzahariZaman\Dosys\Models\Doctor;
use AzahariZaman\Dosys\Models\OrderType;
use AzahariZaman\Dosys\Models\Radiographer;
use AzahariZaman\Dosys\Models\Order;
use AzahariZaman\Dosys\Models\BodyPart;
use AzahariZaman\Dosys\Models\Examination;

class SeedDoctorTable extends Seeder
{
    public function run()
    {
        Doctor::create([ 'name' => 'Lee Woo Guan']);
        Doctor::create([ 'name' => 'Soon Su Yang']);
        
        OrderType::create([ 'name' => 'MRI' ]);
        OrderType::create([ 'name' => 'CT-Scan' ]);
        OrderType::create([ 'name' => 'Ultrasound' ]);
        
        Radiographer::create([ 'name' => 'Malang Menang', 'position' => 'Radiograher']);
        Radiographer::create([ 'name' => 'Nabilah Ahmad', 'position' => 'Radiographer InCharge']);
        Radiographer::create([ 'name' => 'Paul', 'position' => 'Radiograher']);
        
        BodyPart::create([ 'name' => 'ABDOMEN']);
        BodyPart::create([ 'name' => 'ANKLE']);
        BodyPart::create([ 'name' => 'ARM (HUMEROUS)']);
        BodyPart::create([ 'name' => 'ARTERY']);
        BodyPart::create([ 'name' => 'BRAIN']);
        BodyPart::create([ 'name' => 'BREAST']);
        BodyPart::create([ 'name' => 'CALCANEUM']);
        BodyPart::create([ 'name' => 'CARDIAC']);
        BodyPart::create([ 'name' => 'CHEST']);
        BodyPart::create([ 'name' => 'CLAVICLE']);
        BodyPart::create([ 'name' => 'ELBOW JOINT']);
        BodyPart::create([ 'name' => 'EXTREMITIES']);
        BodyPart::create([ 'name' => 'FACIAL & NASAL BONE']);
        BodyPart::create([ 'name' => 'FEMUR (THIGH)']);
        BodyPart::create([ 'name' => 'FOOT']);
        BodyPart::create([ 'name' => 'FOREARM (RADIUS/ULNA)']);
        BodyPart::create([ 'name' => 'HAND']);
        BodyPart::create([ 'name' => 'HIP JOINT']);
        BodyPart::create([ 'name' => 'INTERNAL AUDITORY CANAL']);
        BodyPart::create([ 'name' => 'KNEE']);
        BodyPart::create([ 'name' => 'LOWER LEG (TIBIA/FIBULA)']);
        BodyPart::create([ 'name' => 'MANDIBLE']);
        BodyPart::create([ 'name' => 'MASTOID']);
        BodyPart::create([ 'name' => 'MUSCLES']);
        BodyPart::create([ 'name' => 'NECK']);
        BodyPart::create([ 'name' => 'OPTIC FORAMINA']);
        BodyPart::create([ 'name' => 'ORBIT']);
        BodyPart::create([ 'name' => 'PARANASAL SINUSES']);
        BodyPart::create([ 'name' => 'PELVIS']);
        BodyPart::create([ 'name' => 'SCAPULA']);
        BodyPart::create([ 'name' => 'SHOULDER']);
        BodyPart::create([ 'name' => 'SKULL']);
        BodyPart::create([ 'name' => 'SPINE']);
        BodyPart::create([ 'name' => 'STERNO-CLAVICULAR JOINT']);
        BodyPart::create([ 'name' => 'SUBTALAR JOINT']);
        BodyPart::create([ 'name' => 'TEMPORO-MANDIBULAR JOINT']);
        BodyPart::create([ 'name' => 'THUMB OR SINGLE DIGIT']);
        BodyPart::create([ 'name' => 'THYROID']);
        BodyPart::create([ 'name' => 'WRIST JOINT']);
   
        Examination::create(['group' => 'XR', 'exam_name' => 'Chest (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Chest (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Chest (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Chest (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Abdomen (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Abdomen (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Abdomen (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Kidney, ureter and bladder (KUB) ( Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Lateral pelvimetry']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Antero-posterior (AP) and lateral pelvimetry']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Cervical spine (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Cervical spine (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Cervical spine (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Cervical spine (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Cervical spine (Five views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Thoracic spine (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Thoracic spine (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Thoracic spine (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Lumbo-sacral spine (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Lumbo-sacral spine (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Lumbo-sacral spine (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Lumbo-sacral spine (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Skeletal survey']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Skull (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Skull (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Skull (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Skull (Four views )']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Facial bones (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Facial bones (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Facial bones (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Nasal bones (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Mandible (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Mandible (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Mandible (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Temporo-mandibular joints (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Temporo-mandibular joints (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Temporo-mandibular joints (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Temporo-mandibular joints (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Mastoids  (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Mastoids  (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Mastoids (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Mastoids  (Fours views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Paranasal sinuses (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Paranasal sinuses (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Paranasal sinuses (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Unilateral']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Bilateral']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Orbits (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Orbits (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Orbits (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Internal auditory canal (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Internal auditory canal (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Internal auditory canal (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Shoulder (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Shoulder (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Shoulder (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Shoulder (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Acriomo-clavicular joints-both weight bearing']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Arm (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Arm (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Elbow joint (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Elbow joint (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Elbow joint (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Elbow joint (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Forearm (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Forearm (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Wrist joint (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Wrist joint (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Wrist joint (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Wrist joint (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hand (Single-one view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hand (Single-Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hand (Single - Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hand (Both-One view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hand (Both-Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hand (Both -Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Left Hand for bone age']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Thumb or single digit (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Thumb or single digit (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Clavicle (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Clavicle (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Sterno-clavicular joint (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Sterno-clavicular joint (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Sterno-clavicular joint (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Sternum (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Scapula (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Scapula (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Carpal tunnel view']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Scaphoid views']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Pelvis (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Pelvis (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Pelvis (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hip joint (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hip joint (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hip joint (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hip joint (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Hip joint (Five views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Femur (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Femur (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Knee (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Knee (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Knee (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Knee (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Knee (Five views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Lower leg (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Lower leg (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Ankle (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Ankle (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Ankle (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Ankle (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Ankle (Five views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Foot (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Foot (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Foot (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Both feet (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Both feet (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Subtalar joints (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Subtalar joints (Two views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Subtalar joints (Three views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Subtalar joints (Four views)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Calcaneum (Single view)']);
        Examination::create(['group' => 'XR', 'exam_name' => 'Calcaneum (Two views)']);
        Examination::create(['group' => 'BD', 'exam_name' => 'Dexa']);
        Examination::create(['group' => 'BD', 'exam_name' => 'Ultrasound']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Barium swallow ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Barium meal(double contrast) ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Barium meal and follow through ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Small bowel enema ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Gastrograffin or non-ionic contrast upper gastrointestinal study ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Barium enema(single or double contrast)']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Gastrograffin or non-ionic contrast enema']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Loopogram ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Duodenal intubation ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Oral cholecystogram (single dose) ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Oral cholecystogram (double dose) ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Cystogram ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Ascending urethrogram ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Micturating cystourethrogram']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Retrograde pyelogram-one side ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Retrograde pyelogram-both side ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Ileal conduit study ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Nephrostomy pyelogram-one side ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Nephrostomy pyelogram-both sides']);
        Examination::create(['group' => 'CE', 'exam_name' => 'IVU standard dose contrast ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'IVU standard and tomograms ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'IVU double dose contrast ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'IVU double dose of contrast and tomogram ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'IVU standard dose and delayed radiographs']);
        Examination::create(['group' => 'CE', 'exam_name' => 'IVU double dose of contrast and delayed radiographs']);
        Examination::create(['group' => 'CE', 'exam_name' => 'IVU standard dose & tomograms & delayed radiographs']);
        Examination::create(['group' => 'CE', 'exam_name' => 'IVU double dose & tomograms & delayed radiographs']);
        Examination::create(['group' => 'CE', 'exam_name' => 'T-tube cholangiogram ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Operative cholangiogram-urgent reporting only']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Hysterosalpingogram(Ionic contrast) -screening & reporting only']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Hysterosalpingogram(non-Ionic contrast)-screening & reporting only']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Hysterosalpingogram plus ionic contrast(whole procedure) ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Hysterosalpingogram plus non- ionic contrast(whole procedure) ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Sinogram ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Parotid sialogram-one side']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Parotid sialogram-both sides']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Submandible sialogram-one side ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Submandible sialogram-both sides']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Arthrogram-one side ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Arthrogram-both sides']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Lumbar myelogram (water soluble non-ionic contrast) ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Cervical/thoracic myelogram']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Bronchogram-one side(screening, reporting plus radiographs only) ']);
        Examination::create(['group' => 'CE', 'exam_name' => 'Bronchogram-both sides (screening, reporting plus radiographs only) ']);
        Examination::create(['group' => 'TG', 'exam_name' => 'Tomogram-one plane ']);
        Examination::create(['group' => 'TG', 'exam_name' => 'Tomogram-two planes ']);
        Examination::create(['group' => 'TG', 'exam_name' => 'Tomogram-pituitary fossa AP/lateral ']);
        Examination::create(['group' => 'MM', 'exam_name' => 'Mammography up to four views ']);
        Examination::create(['group' => 'MM', 'exam_name' => 'Mammography & one additional views']);
        Examination::create(['group' => 'MM', 'exam_name' => 'Mammography & two additional views ']);
        Examination::create(['group' => 'MM', 'exam_name' => 'Mammography & limited ultrasound additional ']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Brain (without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Brain ( with non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Brain complex CT ']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Abdomen (without contrast) -CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Abdomen (with non-ionic contrast) -CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Abdomen Two phases-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Abdomen three phases-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Abdomen four phases-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Abdomen complex -CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Pelvis (without contrast) -CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Pelvis (with non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Pelvis complex -CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Spines-cervical or lumbar (without contrast) -CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Spines-cervical or lumbar (with intraspinal non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Spine complex -CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Spines-thoracic(without contrast) -CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Spines-thoracic(with intraspinal non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Spine -thoracic complex-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Chest (without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Chest (with non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Chest complex-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Low dose screening CT of the chest']);
        Examination::create(['group' => 'CT', 'exam_name' => 'HRCT-inspiratory / expiratory']);
        Examination::create(['group' => 'CT', 'exam_name' => 'HRCT-inspiratory plus expiratory']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Neck/Thyroid(without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Neck/Thyroid(with non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Postnasal space and neck (without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Postnasal space and neck (with non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Postnasal space complex-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Orbits (without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Orbits (with non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Orbits complex-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Pituitay fossa(without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Pituitay fossa(with ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'I.A.M (Without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'I.A.M (With non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Total body scan (brain, neck, chest, abdomen & pelvis) (without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Total body scan (with non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Total body scan complex-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Chest, abdomen & pelvis (without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Chest, abdomen & pelvis (with non-ionic contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Chest, abdomen & pelvis complex-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Spiral CT of abdomen & pelvis for renal calculi (without IV contrast)']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Single plane high resolution CT of the paranasal sinuses for sinusitis(without contrast)']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Single plane CT of the paranasal sinuses (without contrast) ']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Single plane CT of the paranasal sinuses (with non-ionic  contrast)']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Abdomen & pelvis (without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Abdomen & pelvis (with contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Abdomen & pelvis complex-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Chest & upper abdomen (without contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Chest & upper abdomen (with contrast)-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'Chest & uppper abdomen complex-CT']);
        Examination::create(['group' => 'CT', 'exam_name' => 'CT two system  (without contrast)']);
        Examination::create(['group' => 'CT', 'exam_name' => 'CT two system (with contrast) ']);
        Examination::create(['group' => 'CT', 'exam_name' => 'CT two system (complex) ']);
        Examination::create(['group' => 'CT', 'exam_name' => 'CT extremities (without contrast) (one region) ']);
        Examination::create(['group' => 'CT', 'exam_name' => 'CT extremities (with contrast) (one region)']);
        Examination::create(['group' => 'CT', 'exam_name' => 'CT extremities complex ']);
        Examination::create(['group' => 'US', 'exam_name' => 'Upper abdomen-U/S']);
        Examination::create(['group' => 'US', 'exam_name' => 'Pelvis-U/S']);
        Examination::create(['group' => 'US', 'exam_name' => 'Abdomen & pelvis-U/S']);
        Examination::create(['group' => 'US', 'exam_name' => 'Kidneys & bladder-U/S']);
        Examination::create(['group' => 'US', 'exam_name' => 'Kidneys & bladder plus residual urine volume estimation-U/S']);
        Examination::create(['group' => 'US', 'exam_name' => 'Brain (neonatal)-U/S']);
        Examination::create(['group' => 'US', 'exam_name' => 'Detailed ultrasound scan of foetus']);
        Examination::create(['group' => 'US', 'exam_name' => 'Thyroid-U/S']);
        Examination::create(['group' => 'US', 'exam_name' => 'Breast -U/S']);
        Examination::create(['group' => 'US', 'exam_name' => 'Doppler ultrasound of extra-cranial carotids']);
        Examination::create(['group' => 'US', 'exam_name' => 'Doppler ultrasound of arteries per region']);
        Examination::create(['group' => 'US', 'exam_name' => 'Doppler ultrasound of veins single limb ']);
        Examination::create(['group' => 'US', 'exam_name' => 'Doppler ultrasound of veins two limbs ']);
        Examination::create(['group' => 'US', 'exam_name' => 'Doppler ultrasound of arteries for single limb']);
        Examination::create(['group' => 'US', 'exam_name' => 'Doppler ultrasound of arteries for two limbs']);
        Examination::create(['group' => 'US', 'exam_name' => 'Musculoskeletal ultrasound per region-U/S']);
        Examination::create(['group' => 'US', 'exam_name' => 'Ultrasound scrotum']);
        Examination::create(['group' => 'US', 'exam_name' => 'Doppler ultrasound for scrotum']);
        Examination::create(['group' => 'US', 'exam_name' => 'Doppler ultrasound for other organs (per organ) ']);
        Examination::create(['group' => 'US', 'exam_name' => 'Endocavitary ultrasound']);
        Examination::create(['group' => 'US', 'exam_name' => 'Heart ultrasound for pericardial disease']);
        Examination::create(['group' => 'US', 'exam_name' => 'Surcharge for each portable ultrasound (normal working hours)']);
        Examination::create(['group' => 'US', 'exam_name' => 'Surcharge for each portable ultrasound (after normal working hours)']);
        Examination::create(['group' => 'SE', 'exam_name' => 'ERCP (screening & reporting only)-simple']);
        Examination::create(['group' => 'SE', 'exam_name' => 'ERCP (screening & reporting only) - complex']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Brain (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Brain (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Brain with magnetic resonance angiography (MRA) (Intracranial)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Brain with MRA plus contrast']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Brain with MRA plus bilateral carotids plus contrast']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRA intracranial or extracranial carotids']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Brain MRV-simple']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Brain MRV-complex']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Pituitary (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Pituitary (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Pituitary (with contrast dynamic)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'I.A.M (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'I.A.M (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'I.A.M plus brain (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'I.A.M plus brain (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Orbits (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Orbits (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Orbits & brain (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Orbits & brain (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Neck (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Neck (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Neck & brain (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Neck & brain (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Brachial plexus (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Brachial plexus (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Mediastinum (without contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Mediastinum (with contrast)-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Cardiac MRI-simple-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Cardiac MRI-intermediate-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Cardiac MRI-complex-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Thoracic MRA-simple']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Thoracic MRA-intermediate']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Thoracic MRA-complex']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Pulmonary MRA-simple']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Pulmonary MRA-intermediate']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Pulmonary MRA - complex']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Surcharge for each 10mL of IV MRI contrast agent']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Upper abdomen - simple-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Upper abdomen - intermediate-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Upper abdomen - complex-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Magnetic resonance cholangiopancreaticography (MRCP)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Magnetic resonance urography']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Upper abdomen MRA - simple']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Upper abdomen MRA - intermediate']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Upper abdomen MRA - complex']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Pelvis - simple-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Pelvis - intermediate-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'Pelvis - complex-MRI']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI pelvimetry']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI whole spine (without contrast) for cord compression']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI whole spine (with contrast) for cord compression']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI cervical spine (without contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI cervical spine (with contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI thoracic spine (without contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI thoracic spine (with contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI lumbar spine (without contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI lumbar spine (with contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI single joint(without contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI single joint(with contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI single region (without contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI single region (with contrast)']);
        Examination::create(['group' => 'MR', 'exam_name' => 'MRI Arthrography (radiologist fee)']);

        
    }
}